# Generated by Django 6.0 on 2025-12-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='content',
        ),
        migrations.AddField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='card',
            name='title',
            field=models.CharField(default='Untitled Card', max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='x',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='card',
            name='y',
            field=models.IntegerField(default=0),
        ),
    ]
