spring.application.name=backend

# ===============================
# POSTGRESQL DATABASE
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/project_db
spring.datasource.username=postgres
spring.datasource.password=root123
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8081
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ensure Spring Boot runs the schema and data SQL files at startup
spring.datasource.initialization-mode=always


# This ensures that data.sql is executed during startup
spring.datasource.data=classpath:data.sql

